export const BUY_CAKE ='BUY_CAKE';
export const BUY_CREAM ='BUY_CREAM';
export const FETCH_REQUEST ='FETCH_REQUEST';
export const FETCH_SUCCESS ='FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_COUNTRY_DATA_REQUEST = 'FETCH_COUNTRY_DATA_REQUEST';
export const FETCH_COUNTRY_DATA_SUCCESS ='FETCH_COUNTRY_DATA_SUCCESS';
export const FETCH_COUNTRY_DATA_FAILURE ='FETCH_COUNTRY_DATA_FAILURE';


export const PRODUCT_SIZE_FILTER = 'PRODUCT_SIZE_FILTER';
export const PRODUCT_PRICE_FILTER = 'PRODUCT_PRICE_FILTER';

export const PRACTICING_RESELECTOR = 'PRACTICING_RESELECTOR';